language: erlang
otp_release:
  - 17.0
  - R16B03-1
  - R16B03
  - R16B02
  - R16B01
  - R16B
before_script:
  - sudo wget -O /etc/apt/sources.list.d/aerospike.list http://packages.aerospike.com/ubuntu/aerospike-ubuntu1204.list
  - sudo apt-get update
  - sudo apt-get install libaerospike2-libevent libaerospike-dev --force-yes
script: ./rebar compile && ./rebar skip_deps=true tests=aerospike_transcoder_test eunit 
