#include "aserl_error.h"

    char* aserl_error_status_string(as_status as_res) {
            switch (as_res) {
    		case AEROSPIKE_ERR_PARAM:
			return "aerospike_err_param";
		case AEROSPIKE_ERR_CLIENT:
			return "aerospike_err_client";
		case AEROSPIKE_OK:
			return "aerospike_ok";
		case AEROSPIKE_ERR_SERVER:
			return "aerospike_err_server";
		case AEROSPIKE_ERR_RECORD_NOT_FOUND:
			return "aerospike_err_record_not_found";
		case AEROSPIKE_ERR_RECORD_GENERATION:
			return "aerospike_err_record_generation";
		case AEROSPIKE_ERR_REQUEST_INVALID:
			return "aerospike_err_request_invalid";
		case AEROSPIKE_ERR_RECORD_EXISTS:
			return "aerospike_err_record_exists";
		case AEROSPIKE_ERR_BIN_EXISTS:
			return "aerospike_err_bin_exists";
		case AEROSPIKE_ERR_CLUSTER_CHANGE:
			return "aerospike_err_cluster_change";
		case AEROSPIKE_ERR_SERVER_FULL:
			return "aerospike_err_server_full";
		case AEROSPIKE_ERR_TIMEOUT:
			return "aerospike_err_timeout";
		case AEROSPIKE_ERR_NO_XDR:
			return "aerospike_err_no_xdr";
		case AEROSPIKE_ERR_CLUSTER:
			return "aerospike_err_cluster";
		case AEROSPIKE_ERR_BIN_INCOMPATIBLE_TYPE:
			return "aerospike_err_bin_incompatible_type";
		case AEROSPIKE_ERR_RECORD_TOO_BIG:
			return "aerospike_err_record_too_big";
		case AEROSPIKE_ERR_RECORD_BUSY:
			return "aerospike_err_record_busy";
		case AEROSPIKE_ERR_SCAN_ABORTED:
			return "aerospike_err_scan_aborted";
		case AEROSPIKE_ERR_UNSUPPORTED_FEATURE:
			return "aerospike_err_unsupported_feature";
		case AEROSPIKE_ERR_BIN_NOT_FOUND:
			return "aerospike_err_bin_not_found";
		case AEROSPIKE_ERR_DEVICE_OVERLOAD:
			return "aerospike_err_device_overload";
		case AEROSPIKE_ERR_RECORD_KEY_MISMATCH:
			return "aerospike_err_record_key_mismatch";
		case AEROSPIKE_ERR_NAMESPACE_NOT_FOUND:
			return "aerospike_err_namespace_not_found";
		case AEROSPIKE_ERR_BIN_NAME:
			return "aerospike_err_bin_name";
		case AEROSPIKE_QUERY_END:
			return "aerospike_query_end";
		case AEROSPIKE_SECURITY_NOT_SUPPORTED:
			return "aerospike_security_not_supported";
		case AEROSPIKE_SECURITY_NOT_ENABLED:
			return "aerospike_security_not_enabled";
		case AEROSPIKE_SECURITY_SCHEME_NOT_SUPPORTED:
			return "aerospike_security_scheme_not_supported";
		case AEROSPIKE_INVALID_COMMAND:
			return "aerospike_invalid_command";
		case AEROSPIKE_INVALID_FIELD:
			return "aerospike_invalid_field";
		case AEROSPIKE_ILLEGAL_STATE:
			return "aerospike_illegal_state";
		case AEROSPIKE_INVALID_USER:
			return "aerospike_invalid_user";
		case AEROSPIKE_USER_ALREADY_EXISTS:
			return "aerospike_user_already_exists";
		case AEROSPIKE_INVALID_PASSWORD:
			return "aerospike_invalid_password";
		case AEROSPIKE_EXPIRED_PASSWORD:
			return "aerospike_expired_password";
		case AEROSPIKE_FORBIDDEN_PASSWORD:
			return "aerospike_forbidden_password";
		case AEROSPIKE_INVALID_CREDENTIAL:
			return "aerospike_invalid_credential";
		case AEROSPIKE_INVALID_ROLE:
			return "aerospike_invalid_role";
		case AEROSPIKE_INVALID_PRIVILEGE:
			return "aerospike_invalid_privilege";
		case AEROSPIKE_NOT_AUTHENTICATED:
			return "aerospike_not_authenticated";
		case AEROSPIKE_ROLE_VIOLATION:
			return "aerospike_role_violation";
		case AEROSPIKE_ERR_UDF:
			return "aerospike_err_udf";
		case AEROSPIKE_ERR_LARGE_ITEM_NOT_FOUND:
			return "aerospike_err_large_item_not_found";
		case AEROSPIKE_ERR_INDEX_FOUND:
			return "aerospike_err_index_found";
		case AEROSPIKE_ERR_INDEX_NOT_FOUND:
			return "aerospike_err_index_not_found";
		case AEROSPIKE_ERR_INDEX_OOM:
			return "aerospike_err_index_oom";
		case AEROSPIKE_ERR_INDEX_NOT_READABLE:
			return "aerospike_err_index_not_readable";
		case AEROSPIKE_ERR_INDEX:
			return "aerospike_err_index";
		case AEROSPIKE_ERR_INDEX_NAME_MAXLEN:
			return "aerospike_err_index_name_maxlen";
		case AEROSPIKE_ERR_INDEX_MAXCOUNT:
			return "aerospike_err_index_maxcount";
		case AEROSPIKE_ERR_QUERY_ABORTED:
			return "aerospike_err_query_aborted";
		case AEROSPIKE_ERR_QUERY_QUEUE_FULL:
			return "aerospike_err_query_queue_full";
		case AEROSPIKE_ERR_QUERY_TIMEOUT:
			return "aerospike_err_query_timeout";
		case AEROSPIKE_ERR_QUERY:
			return "aerospike_err_query";
		case AEROSPIKE_ERR_UDF_NOT_FOUND:
			return "aerospike_err_udf_not_found";
		case AEROSPIKE_ERR_LUA_FILE_NOT_FOUND:
			return "aerospike_err_lua_file_not_found";
		case AEROSPIKE_ERR_LDT_INTERNAL:
			return "aerospike_err_ldt_internal";
		case AEROSPIKE_ERR_LDT_NOT_FOUND:
			return "aerospike_err_ldt_not_found";
		case AEROSPIKE_ERR_LDT_UNIQUE_KEY:
			return "aerospike_err_ldt_unique_key";
		case AEROSPIKE_ERR_LDT_INSERT:
			return "aerospike_err_ldt_insert";
		case AEROSPIKE_ERR_LDT_SEARCH:
			return "aerospike_err_ldt_search";
		case AEROSPIKE_ERR_LDT_DELETE:
			return "aerospike_err_ldt_delete";
		case AEROSPIKE_ERR_LDT_INPUT_PARM:
			return "aerospike_err_ldt_input_parm";
		case AEROSPIKE_ERR_LDT_TYPE_MISMATCH:
			return "aerospike_err_ldt_type_mismatch";
		case AEROSPIKE_ERR_LDT_NULL_BIN_NAME:
			return "aerospike_err_ldt_null_bin_name";
		case AEROSPIKE_ERR_LDT_BIN_NAME_NOT_STRING:
			return "aerospike_err_ldt_bin_name_not_string";
		case AEROSPIKE_ERR_LDT_BIN_NAME_TOO_LONG:
			return "aerospike_err_ldt_bin_name_too_long";
		case AEROSPIKE_ERR_LDT_TOO_MANY_OPEN_SUBRECS:
			return "aerospike_err_ldt_too_many_open_subrecs";
		case AEROSPIKE_ERR_LDT_TOP_REC_NOT_FOUND:
			return "aerospike_err_ldt_top_rec_not_found";
		case AEROSPIKE_ERR_LDT_SUB_REC_NOT_FOUND:
			return "aerospike_err_ldt_sub_rec_not_found";
		case AEROSPIKE_ERR_LDT_BIN_DOES_NOT_EXIST:
			return "aerospike_err_ldt_bin_does_not_exist";
		case AEROSPIKE_ERR_LDT_BIN_ALREADY_EXISTS:
			return "aerospike_err_ldt_bin_already_exists";
		case AEROSPIKE_ERR_LDT_BIN_DAMAGED:
			return "aerospike_err_ldt_bin_damaged";
		case AEROSPIKE_ERR_LDT_SUBREC_POOL_DAMAGED:
			return "aerospike_err_ldt_subrec_pool_damaged";
		case AEROSPIKE_ERR_LDT_SUBREC_DAMAGED:
			return "aerospike_err_ldt_subrec_damaged";
		case AEROSPIKE_ERR_LDT_SUBREC_OPEN:
			return "aerospike_err_ldt_subrec_open";
		case AEROSPIKE_ERR_LDT_SUBREC_UPDATE:
			return "aerospike_err_ldt_subrec_update";
		case AEROSPIKE_ERR_LDT_SUBREC_CREATE:
			return "aerospike_err_ldt_subrec_create";
		case AEROSPIKE_ERR_LDT_SUBREC_DELETE:
			return "aerospike_err_ldt_subrec_delete";
		case AEROSPIKE_ERR_LDT_SUBREC_CLOSE:
			return "aerospike_err_ldt_subrec_close";
		case AEROSPIKE_ERR_LDT_TOPREC_UPDATE:
			return "aerospike_err_ldt_toprec_update";
		case AEROSPIKE_ERR_LDT_TOPREC_CREATE:
			return "aerospike_err_ldt_toprec_create";
		case AEROSPIKE_ERR_LDT_FILTER_FUNCTION_BAD:
			return "aerospike_err_ldt_filter_function_bad";
		case AEROSPIKE_ERR_LDT_FILTER_FUNCTION_NOT_FOUND:
			return "aerospike_err_ldt_filter_function_not_found";
		case AEROSPIKE_ERR_LDT_KEY_FUNCTION_BAD:
			return "aerospike_err_ldt_key_function_bad";
		case AEROSPIKE_ERR_LDT_KEY_FUNCTION_NOT_FOUND:
			return "aerospike_err_ldt_key_function_not_found";
		case AEROSPIKE_ERR_LDT_TRANS_FUNCTION_BAD:
			return "aerospike_err_ldt_trans_function_bad";
		case AEROSPIKE_ERR_LDT_TRANS_FUNCTION_NOT_FOUND:
			return "aerospike_err_ldt_trans_function_not_found";
		case AEROSPIKE_ERR_LDT_UNTRANS_FUNCTION_BAD:
			return "aerospike_err_ldt_untrans_function_bad";
		case AEROSPIKE_ERR_LDT_UNTRANS_FUNCTION_NOT_FOUND:
			return "aerospike_err_ldt_untrans_function_not_found";
		case AEROSPIKE_ERR_LDT_USER_MODULE_BAD:
			return "aerospike_err_ldt_user_module_bad";
		case AEROSPIKE_ERR_LDT_USER_MODULE_NOT_FOUND:
			return "aerospike_err_ldt_user_module_not_found";

            }
                return "aerospike_err_unkown";
    }